### ISSUE TITLE
TODO'S

### ISSUE THREAD

**Issue by murtaza98** [murtaza98/BookZone#13]
- [ ] register
- [ ] login
- [ ] register page javascript
- [ ] bookmark redirect
- [ ] price on index page books
- [ ] search function
- [ ] individual category page
